### PR TITLE
Support multi-currency on invoices and bank transactions

### PR DESCRIPTION
**Pull request by richdrich**
The Xero API supports multi-currency transactions (when this functionality is enabled for the user's account).

This change adds the fields:
```BankTransaction#currency_code``` and ```BankTransaction#currency_rate```

```Invoice#currency_rate```

We've been running this off a forked gem at Sharesight for just over a year, and we're looking to move back onto the released ```xero_gateway```

Let me know any questions?

### CODE REVIEW

**Comment by richdrich** [comment]
Just to note CI seems broken:
```
An error occurred while installing oauth (0.5.3), and Bundler cannot continue.
Make sure that `gem install oauth -v '0.5.3'` succeeds before bundling.
```

**Comment by nikz** [comment]
@richdrich 

re: CI: yes, we need to drop 1.9.3 support really.

re: your PR: it looks great, but it's a fairly large one - give us a wee while to review it properly, thanks for merging back in to mainline! We really appreciate it.

**Comment by richdrich** [comment]
Oops. Didn't mean to delete this PR :-)

**Comment by alto** [comment]
+1

**Comment by nikz** [comment]
Thanks for the PR! Have had a chance to look through, and it all looks good to me. 

We'll let it bed in with people who are brave enough to use `master` and then do a new release in a week or so.

**Pull request merged**
